### ISSUE TITLE
Fail to export "NuMaker-mbed-OS-6-AWS-IoT" to uvision project.

### ISSUE THREAD

**Issue by francesang** [cyliangtw/NuMaker-mbed-OS-6-AWS-IoT#1]
Dear Sir,

I would like to know if this binary match with these repo?

NuMaker_IoT_M2354\M2354_Series_BSP_CMSIS_V3.00.003a\SampleCode\NuMakerIoT\mbedOS6_AWS_IoT\numaker-mbed-os-6-aws-iot.bin
I successfully copy this bin to Numaker IoT M2354 and it can run properly.
But, i clone and build this repo to mbed desktop but I fail to run the binary.
Do you know the reason?

I also try to export this project to uVision keil project, but seem it does not support.

Thank you in advance.

BR,
Frances

**Comment by cyliangtw** [comment]
For normal target, export by "mbed export -i UVISION6".
For TrustZone target, tool chain seems not support export IDE prj.
Did you follow any quick start guide to build & run the bin file ?

**Comment by francesang** [comment]
Thanks for you quick reply.>For normal target, export by "mbed export -i UVISION6Thanks. I will try.I import the project through URL.then click build clean and then debug.When compilation done, I can see the binary and copy it to the nulink mcu USB. Or do you have a start guide for me to follow? Frances.On Jul 29, 2022 6:45 PM, Chris Liang ***@***.***> wrote:
For normal target, export by "mbed export -i UVISION6".
For TrustZone target, tool chain seems not support export IDE prj.
Did you follow any quick start guide to build & run the bin file ?

**Comment by cyliangtw** [comment]
About quick start guide, please refer to https://www.nuvoton.com/board/numaker-iot-m2354/?index=2

**Comment by cyliangtw** [comment]
I guessed you should fixed it after follow quick start guide or [README.md](https://github.com/cyliangtw/NuMaker-mbed-OS-6-AWS-IoT#readme).
I close this issue and you could reopen if still suffer issue.
